- hosts: localhost
  become: true
  pre_tasks:
    - name: pre-run | update package cache
      apt: update_cache=yes
      changed_when: False
  tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/cron.yml
    - import_tasks: tasks/distro_packages.yml
    - import_tasks: tasks/distro_clean.yml
    - import_tasks: tasks/gnome.yml
    - import_tasks: tasks/doom.yml
